server:
  port: 9002
  
spring:
  application:
     name: advertise-service
  config:
    import: configserver:http://localhost:8888
  zipkin:
     base-url: http://localhost:9411
management:  endpoints:    web:      exposure:        include: "*"
      base-path: "/olx-monitor"
  health:    circuitbreakers:      enabled: true
  endpoint:
    health:
      show-details: always
resilience4j:
  circuitbreaker:
    instances:
      STATUSNAME-FROM-MASTER-DATA-SERVICE:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
      CATEGORYNAME-FROM-MASTER-DATA-SERVICE:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true      