server:
   port: 8888
spring:
   application:
      name: configuration-server
   cloud:
     config:
        server:
           git:
              uri: https://github.com/akhi9878/olx-config
              default-label: main
              username: akhi9878
              clone-on-start: true