server:
  port: 9001
spring:
   application:     name: masterdata-service  
   config:
    import: configserver:http://localhost:8888      
   zipkin:
     base-url: http://localhost:9411
management:  endpoints:    web:      exposure:        include: "*"      base-path: /olx-monitor  endpoint:    health:      show-details: always

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true